re-enable `assets` tests.
These were written to juice coverage numbers, but actually did catch a bug in assets, so I'd like to keep them.

If `CGO_ENABLED=0` isn't set when building `satellite-amd64-linux`, it'll depend on libc.

```
--- FAIL: TestSatelliteAmd64LinuxIsElf (0.00s)
    assets_test.go:22:
                Error Trace:    /home/alona/dev/gpuctl/internal/assets/assets_test.go:22
                Error:          Should be empty, but was [libc.so.6]
                Test:           TestSatelliteAmd64LinuxIsElf
                Messages:       satellite binary has imports, but should be static binary
FAIL
FAIL    github.com/gpuctl/gpuctl/internal/assets        0.002s
FAIL
```

For maximum likelihood of working on the remote machine, we'd like to ensure we only use the linux syscall interface instead.